# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/hgiesel/Developer/repos/anki_frozen_fields/designer/settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Settings(object):
    def setupUi(self, Settings):
        Settings.setObjectName("Settings")
        Settings.setWindowModality(QtCore.Qt.WindowModal)
        Settings.resize(331, 116)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Settings.sizePolicy().hasHeightForWidth())
        Settings.setSizePolicy(sizePolicy)
        self.gridLayout = QtWidgets.QGridLayout(Settings)
        self.gridLayout.setObjectName("gridLayout")
        self.toggleAllShortcut = QtWidgets.QKeySequenceEdit(Settings)
        self.toggleAllShortcut.setObjectName("toggleAllShortcut")
        self.gridLayout.addWidget(self.toggleAllShortcut, 1, 1, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(Settings)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 2, 1, 1, 2)
        self.toggleAllLabel = QtWidgets.QLabel(Settings)
        self.toggleAllLabel.setObjectName("toggleAllLabel")
        self.gridLayout.addWidget(self.toggleAllLabel, 1, 0, 1, 1)
        self.toggleFieldShortcut = QtWidgets.QKeySequenceEdit(Settings)
        self.toggleFieldShortcut.setObjectName("toggleFieldShortcut")
        self.gridLayout.addWidget(self.toggleFieldShortcut, 0, 1, 1, 1)
        self.toggleFieldLabel = QtWidgets.QLabel(Settings)
        self.toggleFieldLabel.setObjectName("toggleFieldLabel")
        self.gridLayout.addWidget(self.toggleFieldLabel, 0, 0, 1, 1)

        self.retranslateUi(Settings)
        self.buttonBox.accepted.connect(Settings.accept)
        self.buttonBox.rejected.connect(Settings.reject)
        QtCore.QMetaObject.connectSlotsByName(Settings)

    def retranslateUi(self, Settings):
        _translate = QtCore.QCoreApplication.translate
        Settings.setWindowTitle(_translate("Settings", "Ze Frozen Fields Settings"))
        self.toggleAllShortcut.setToolTip(_translate("Settings", "<html><head/><body><p>The &quot;Edit Current&quot; window may be in one of two modes: obscure mode, or presentation mode. While in presentation mode, the persistent editor will <span style=\" font-weight:600;\">not</span> obscure the fields, when the card is currently showing the frontside of the card. This shortcut can be triggered in the editor. (default: &quot;Ctrl+P&quot;)</p></body></html>"))
        self.toggleAllLabel.setToolTip(_translate("Settings", "<html><head/><body><p>The &quot;Edit Current&quot; window may be in one of two modes: obscure mode, or presentation mode. While in presentation mode, the persistent editor will <span style=\" font-weight:600;\">not</span> obscure the fields, when the card is currently showing the frontside of the card. This shortcut can be triggered in the editor. (default: &quot;Ctrl+P&quot;)</p></body></html>"))
        self.toggleAllLabel.setText(_translate("Settings", "Shortcut: Toggle All"))
        self.toggleFieldShortcut.setToolTip(_translate("Settings", "<html><head/><body><p>Use this shortcut to flip between the front and the back of a given card. Can be used in the reviewer window. (default: &quot;C&quot;)</p></body></html>"))
        self.toggleFieldLabel.setToolTip(_translate("Settings", "<html><head/><body><p>Use this shortcut to flip between the front and the back of a given card. Can be used in the reviewer window. (default: &quot;C&quot;)</p></body></html>"))
        self.toggleFieldLabel.setText(_translate("Settings", "Shortcut: Toggle Field"))
